[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 1
fuzz = { runs = 1000 }
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
base_sepolia = "https://base-sepolia.drpc.org"
base = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }